### ISSUE TITLE
Upload all Tracking (MH, RH, EH) scripts into the repository

### ISSUE THREAD

**Issue by FilipsFedotovs** [FilipsFedotovs/ANNADEA#1]
Copy all items from EDER-GNN.

**Comment by FilipsFedotovs** [comment]
Small bug was discovered during the testing where the **MH2_TrainModel_Sub.py** was throwing the following error:
*Traceback (most recent call last):
  File "/afs/cern.ch/work/f/ffedship/private/SND/Local/ANNADEA_DEV/ANNADEA/Code/Utilities/MH2_TrainModel_Sub.py", line 222, in <module>
    main(sys.argv[1:])
  File "/afs/cern.ch/work/f/ffedship/private/SND/Local/ANNADEA_DEV/ANNADEA/Code/Utilities/MH2_TrainModel_Sub.py", line 205, in main
    train_loss, itr= train(model, device,TrainSamples, optimizer)
  File "/afs/cern.ch/work/f/ffedship/private/SND/Local/ANNADEA_DEV/ANNADEA/Code/Utilities/MH2_TrainModel_Sub.py", line 89, in train
    w = model(data.x, data.edge_index, data.edge_attr)
  File "/afs/cern.ch/user/f/ffedship/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/afs/cern.ch/work/f/ffedship/private/SND/Local/ANNADEA_DEV/ANNADEA/Code/Utilities/UtilityFunctions.py", line 991, in forward
    x1, edge_attr_1 = self.in_w1(x, edge_index, edge_attr)
  File "/afs/cern.ch/user/f/ffedship/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/afs/cern.ch/work/f/ffedship/private/SND/Local/ANNADEA_DEV/ANNADEA/Code/Utilities/MH_IN.py", line 51, in forward
    x_tilde = self.propagate(edge_index, x=x, edge_attr=edge_attr, size=None)
  File "/afs/cern.ch/user/f/ffedship/.local/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 317, in propagate
    out = self.message(**msg_kwargs)
  File "/afs/cern.ch/work/f/ffedship/private/SND/Local/ANNADEA_DEV/ANNADEA/Code/Utilities/MH_IN.py", line 57, in message
    self.E_tilde = self.R1(m)
  File "/afs/cern.ch/user/f/ffedship/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/afs/cern.ch/work/f/ffedship/private/SND/Local/ANNADEA_DEV/ANNADEA/Code/Utilities/MH_IN.py", line 19, in forward
    return self.layers(m)
  File "/afs/cern.ch/user/f/ffedship/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/afs/cern.ch/user/f/ffedship/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/afs/cern.ch/user/f/ffedship/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
return forward_call(*input, **kwargs)
  File "/afs/cern.ch/user/f/ffedship/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/afs/cern.ch/user/f/ffedship/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/afs/cern.ch/user/f/ffedship/.local/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/afs/cern.ch/user/f/ffedship/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (406x15 and 9x20)*

The error was caused by the values that were set in the **Parameters.py** file:
**num_node_features** and **num_edge_features** were set to 3 which is wrong. Currently we are using the value of 5 (x,y,z,tx,ty). The new number wasn't reflected in the migrated version. The issue has been fixed by setting those values to 5.

**Comment by FilipsFedotovs** [comment]
All bugs have been resolved. The current version is still not ready for the first release as Wenqing will look into the code and improve user experience. Closing this issue as migration was successful.
